version: '3'

networks:
  ics:
    name: ics
    driver: bridge
    ipam:
      config: 
        - subnet: 192.168.192.0/24

volumes:
  grafana-data:
  prometheus-data:

services:

  tshark:
    image: oihan27/tshark:tshark
    build: 
      context: ./Tshark
    container_name: tshark
    volumes:
      - /Tshark:/home/captures
    privileged: true
    network_mode: host
    restart: unless-stopped

  interface:
    image: frolvlad/alpine-gxx
    container_name: interface
    command: sh -c "g++ /Interface/simlink.cpp -o Interface/simlink -pthread && tail -F /dev/null" #Ejecuta el archivo .cpp con la ayuda del .cfg
    volumes: 
      - ../../../wwtp/interface_simLink:/Interface
    restart: unless-stopped
    networks:
      ics:
        ipv4_address: 192.168.192.2

  matlab_simulink: #Contiene el programa de Matlab/Simulink
    image: sflorenz05/matlab_simulink:v0.3
    container_name: matlab_simulink
    shm_size: 512M
    ports:
      - "5901:5901"
      - "6080:6080"
    command: -vnc
    volumes:
      - /wwtp/simulink:/home/matlab/Documents/MATLAB/simulink
    restart: unless-stopped
    networks:
      ics:
        ipv4_address: 192.168.192.4

  openplc: #Contiene el OpenPLC runtime
    image: sflorenz05/open-plc:v0.1
    container_name: openplc
    ports:
      - "502:502"
      - "8080:8080"
    command: -privileged
    restart: unless-stopped
    networks:
      ics:
        ipv4_address: 192.168.192.3

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus
  #   restart: unless-stopped
  #   networks:
  #     - ics

  # prometheus:
  #   image: prom/prometheus:v2.33.0
  #   container_name: prometheus
  #   volumes:
  #      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #      - prometheus-data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--storage.tsdb.retention.time=120h'
  #     - '--web.enable-lifecycle'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
  #   ports:
  #     - "9090:9090"
  #   depends_on:
  #     - cadvisor
  #   restart: unless-stopped
  #   networks:
  #     - ics
  #   links:
  #     - cadvisor:cadvisor

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   privileged: true
  #   pid: host
  #   network_mode: host
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   expose:
  #     - 8080
  #   restart: unless-stopped

  clientperf1:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf1
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.5
    environment:
      - AUTO_SERVER_HOST=openplc