version: '3'

networks:
  ics:
    name: ics
    driver: bridge
    ipam:
      config: 
        - subnet: 192.168.192.0/24

services:
  
  tshark:
    image: oihan27/tshark:tshark
    build: 
      context: ./Tshark
    container_name: tshark
    volumes:
      - /Tshark:/home/captures
    privileged: true
    network_mode: host
    restart: unless-stopped

  interface:
    image: frolvlad/alpine-gxx
    container_name: interface
    command: sh -c "g++ /Interface/simlink.cpp -o Interface/simlink -pthread && tail -F /dev/null" #Ejecuta el archivo .cpp con la ayuda del .cfg
    volumes: 
      - ../../../wwtp/interface_simLink:/Interface
    restart: unless-stopped
    networks:
      ics:
        ipv4_address: 192.168.192.2

  matlab_simulink: #Contiene el programa de Matlab/Simulink
    image: sflorenz05/matlab_simulink:v0.3
    container_name: matlab_simulink
    shm_size: 512M
    ports:
      - "5901:5901"
      - "6080:6080"
    command: -vnc
    volumes:
      - /wwtp/simulink:/home/matlab/Documents/MATLAB/simulink
    restart: unless-stopped
    networks:
      ics:
        ipv4_address: 192.168.192.4

  openplc: #Contiene el OpenPLC runtime
    image: sflorenz05/open-plc:v0.1
    container_name: openplc
    ports:
      - "502:502"
      - "8080:8080"
    command: -privileged
    restart: unless-stopped
    networks:
      ics:
        ipv4_address: 192.168.192.3

  clientperf1:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf1
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.5
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf2:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf2
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.6
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf3:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf3
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.7
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf4:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf4
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.8
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf5:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf5
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.9
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf6:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf6
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.10
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf7:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf7
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.11
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf8:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf8
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.12
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf9:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf9
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.13
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf10:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf10
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.14
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf11:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf11
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.15
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf12:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf12
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.16
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf13:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf13
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.17
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf14:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf14
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.18
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf15:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf15
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.19
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf16:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf16
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.20
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf17:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf17
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.21
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf18:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf18
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.22
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf19:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf19
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.23
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf20:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf20
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.24
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf21:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf21
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.25
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf22:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf22
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.26
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf23:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf23
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.27
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf24:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf24
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.28
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf25:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf25
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.29
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf26:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf26
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.30
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf27:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf27
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.31
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf28:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf28
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.32
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf29:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf29
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.33
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf30:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf30
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.34
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf31:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf31
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.35
    environment:
      - AUTO_SERVER_HOST=openplc

  clientperf32:
    image: oihan27/tcpclient:performance #Ejecuta performance.py
    container_name: clientperf32
    build: 
      context: ./Clients
    restart: unless-stopped
    depends_on:
      - openplc
    networks:
      ics:
        ipv4_address: 192.168.192.36
    environment:
      - AUTO_SERVER_HOST=openplc